language: julia 
os:
  - windows
julia:
  - 1.8
branches:
  only:
    - master
coveralls: true
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.8
      os: windows
      script: 
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.lj
        after_success: skip 