name: Runtests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.8.5']
        julia-arch: [x64]
        os: [windows-latest] # [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
        with:
          flags: '--color=yes --verbosity=verbose'
      - name: Coverage
        run: julia -e 'using Coverage; Codecov.submit(process_folder())'
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}